openapi: 3.0.0

info:
  title: Blog API
  version: 0.0.1
  
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
            example: ['user1','user2','user3','user4']
    post:
      summary: Creates a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
            examples:
              username:
                summary: Preferred username that will be associated with the a blog.
                value:
                  name: pakapaka
              password:
                summary: Preferred password
                value:
                  name: myverystrongpassword
      responses:
        '201':
          description: Created
        '400':
          description: Invalid registration credentials
          
  /blogs:
    get:
      summary: Gets a list of all blogs
      responses:
        '200':
          description: A list of hashes containing the blog id as the key and the title as the value
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
              example:
                id: 1
                title: first_blog
                id: 2
                title: second_blog
    post:
      summary: Creates a new blog post
      requestBody:
        required: true
        content:
          application/json:
            schema:
            type: object
            properties:
              title:
                type: string
              body:
                type: string
      responses:
        '201':
          description: Created
      
                
  /blogs/{blogId}:
    get:
      summary: Returns a single blog by ID
      parameters:
        name: blogId
        in: path
        required: true
        schema:
          type: integer
          format: int64
          minimum: 1
      responses:
        '200':
          description: Blog object
          content:
            application/json:
              schema:
                type: object
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    blog:
                      type: object
                      properties:
                        title:
                          type: string
                        body:
                          type: string
        '404':
          description: Not found
    patch:
      summary: Updates an existing post
      parameters:
        name: blogId
        in: path
        required: true
        schema:
          type: integer
          format: int64
          minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
              new_title:
                type: string
              new_body:
                type: string
      responses:
        '200':
          description: Updated
        '404':
          description: Not found
        '400':
          description: Invalid input
    delete:
      summary: Deletes an existing post
      parameters:
        name: blogId
        in: path
        required: true
        schema:
          type: integer
          format: int64
          minimum: 1
      responses:
        '200':
          description: Deleted
        '404':
          description: Not found
          
  /blogs/{blogId}/comments:
    get:
      summary: Get a list of comments associated with a single post
      parameters:
        name: blogId
        in: path
        required: true
        schema:
          type: integer
          format: int64
          minimum: 1
      responses:
        '200':
          description: Returns an array of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    commenter:
                      type: string
                    comment_body:
                      type: string
              examples:
                commenter:
                  value: first_commenter
                comment_body:
                  value: comment_body
        '404':
          description: No comments for that blog
    post:
      summary: Post a comment to a blog
      paramenters:
        name: blogId
        in: path
        required: true
        schema:
          type: integer
          format: int64
          minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                commenter:
                  type: string
                Comment:
                  type: string
      responses:
        '201':
          description: Comment added